name = "ARC Unofficial"
author = "Defiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0715998080b4481fde35e1eaf72f15592df6f5767b10f215595cda1f4971d566"

[versions]
fabric = "0.18.2"
minecraft = "26.1"
