name = "ARC Unofficial"
author = "Defiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b215b18b62554eee41e008c9b0408045790e1c99e14584832a6bb6a2fab503f"

[versions]
fabric = "0.18.2"
minecraft = "26.1"
