name = "ARC Unofficial"
author = "Defiant"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c76e07f834219af3bfb2e05f656f1f801797a5e6f4ec8913bb09e8f530fd4e8e"

[versions]
fabric = "0.18.2"
minecraft = "1.21.11"
